FROM ncsdk/base:build

# Copy over the NCSDK
COPY ./ ncsdk/

# Set the current working directory to the cloned ncsdk directory
WORKDIR "/ncsdk"

# Install tensorflow
RUN pip3 install ./tensorflow-1.9.0-cp35-none-linux_armv7l.whl
RUN rm -rf /ncsdk
