FROM ubuntu:16.04

# Install necessary packages for the installer
RUN apt-get update && apt-get install -y \
    apt-utils \
    lsb-release \
    build-essential \
    sed \
    sudo \
    tar \
    udev \
    wget \
    libusb-1.0-0-dev \
    python3-dev \
    python3 python3-pip python-pip \
    libatlas-base-dev \
    && apt-get clean

# Copy over the NCSDK
COPY ./ ncsdk/

# Set the current working directory to the cloned ncsdk directory
WORKDIR "/ncsdk"

# Run the installer
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python2 get-pip.py
RUN python3 get-pip.py
# RUN pip3 install ./tensorflow-1.9.0-cp35-none-linux_armv7l.whl

RUN make install
WORKDIR "api/src"
RUN sudo make clean && sudo make get_mvcmd && sudo make basicinstall NO_BOOT=yes NO_RESET=yes && sudo make pythoninstall
WORKDIR "../../"
