FROM ncsdk-base

ENV TENSORFLOW tensorflow-1.9.0-cp35-none-linux_armv7l.whl

# Copy over the NCSDK
COPY ./installation/$TENSORFLOW .

# Install tensorflow
#RUN pip3 install ./$TENSORFLOW
# RUN rm -rf /$TENSORFLOW
